---
abstract: 'Remote lib for use some modules without install'
author:
  - 'Mikhail Che <m.che#aukama.dyndns.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-remote
provides:
  lib::remote:
    file: lib/lib/remote.pm
    version: 0.01
requires:
  LWP::UserAgent: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
